[package]
name = "hotg-rune-proc-block-macros"
version = "0.5.0"
edition = "2018"
authors = ["The Rune Developers <developers@hotg.ai>"]
license = "MIT OR Apache-2.0"
homepage = "https://hotg.dev/"
repository = "https://github.com/hotg-ai/rune"
categories = ["no-std", "science", "wasm"]
keywords = ["rune", "proc-block", "macro"]
description = "Procedural macros for the rune-proc-block crate."
readme = "README.md"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
hotg-rune-core = { path = "../../crates/rune-core", version = "0.5.0", default-features = false }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
syn = { version = "1.0.72", features = ["extra-traits", "full"] }

[dev-dependencies]
difference = "2.0.0"
pretty_assertions = "0.7.2"
hotg-rune-proc-blocks = { path = "../proc-blocks", version = "^0.5.0"}
