---
image: runicos/base
pipeline:
  audio:
    capability: SOUND
    outputs:
      - type: I16
        dimensions:
          - 16000
    args:
      hz: 16000
      sample-duration-ms: 1000
  fft:
    proc-block: "hotg-ai/rune#proc_blocks/fft"
    inputs:
      - audio
    outputs:
      - type: I8
        dimensions:
          - 1960
  model:
    model: "./model_6dim_ver2.tflite"
    inputs:
      - fft
    outputs:
      - type: I8
        dimensions:
          - 6
  serial:
    out: serial
    inputs:
      - model
