[package]
name = "rune-native"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.41"
rune-runtime = { path = "../../crates/runtime", version = "0.4.0-dev"  }
rune-wasmer-runtime = { path = "../../crates/wasmer-runtime", version = "0.4.0-dev" , optional = true }
runicos-base-runtime = { path = "../../images/runicos-base/runtime", version = "0.4.0-dev" , default-features = false }
safer-ffi = { version = "0.0.6", features = ["proc_macros"] }

[features]
c-headers = ["safer-ffi/headers"]
wasmer-runtime = ["rune-wasmer-runtime"]
tflite = ["runicos-base-runtime/tflite"]
