[package]
name = "rune-ffi"
version = "0.1.0"
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
env_logger = "0.8.3"
libc = "0.2.87"
log = "0.4.14"
rune-codegen = { path = "../../crates/codegen" }
rune-runtime = { path = "../../crates/runtime" }
rune-wasmer-runtime = { path = "../../crates/wasmer-runtime" }
rune-syntax = { path = "../../crates/syntax" }
runic-types = { path = "../../crates/runic-types" }
runicos-base-runtime = { path = "../../images/runicos-base/runtime" }

[lib]
name = "rune"
crate-type = ["cdylib", "staticlib", "rlib"]

[dev-dependencies]
cbindgen = "0.19.0"
tempfile = "3.2.0"
