[package]
name = "hotg-rune-cli"
version = "0.5.0"
edition = "2018"
authors = ["The Rune Developers <developers@hotg.ai>"]
description = "A self-sufficient runtime for TinyML Containers."
license = "MIT OR Apache-2.0"
homepage = "https://hotg.dev/"
repository = "https://github.com/hotg-ai/rune"
categories = ["science", "wasm", "command-line-utilities"]
keywords = ["rune", "tinyml", "container", "machine", "learning"]
readme = "README.md"

[dependencies]
anyhow = "1.0.38"
build-info = { version = "0.0.23", features = ["serde"] }
chrono = { version = "0.4.19", features = ["std"] }
clap = "2.33.3"
codespan-reporting = "0.11.0"
dirs = "3.0.1"
env_logger = "0.8.1"
hound = "3.4.0"
image = "0.23.14"
indexmap = "1.6.2"
log = { version = "0.4.11" }
once_cell = "1.7.0"
petgraph = "0.5.1"
rand = "0.8.3"
hotg-rune-codegen = { path = "../codegen", version = "^0.5.0"}
hotg-rune-runtime = { path = "../runtime", version = "^0.5.0"}
hotg-rune-syntax = { path = "../syntax", version = "^0.5.0"}
hotg-rune-wasmer-runtime = { path = "../wasmer-runtime", version = "^0.5.0"}
hotg-rune-core = { path = "../rune-core", version = "^0.5.1-dev"}
hotg-runicos-base-runtime = { path = "../../images/runicos-base/runtime", version = "^0.5.0", features = ["tflite"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
strum = { version = "0.20.0", features = ["derive"] }
tflite = "0.9.5"
wasmparser = "0.78.2"
runecoral = { git = "https://github.com/hotg-ai/librunecoral" }

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.7"
tempfile = "3.2.0"
walkdir = "2.3.2"
criterion = "0.3"
tempdir = "0.3"

[build-dependencies]
build-info-build = "0.0.23"

[[bench]]
name = "rune_benchmark"
harness = false
