edition = "2018"
fn_single_line = true
imports_granularity= "Crate"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = false
report_fixme = "Always"
report_todo = "Always"
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
