fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
report_fixme = "Unnumbered"
report_todo = "Unnumbered"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
