[workspace]
resolver = "2"
members = [
    "crates/*",
    "bindings/*",
    "images/runicos-base/*",
    "integration-tests",
    "proc-blocks/*",
]

[patch.crates-io]
serde_yaml = { git = "https://github.com/hotg-ai/serde-yaml", branch = "spans" }
