[workspace]
members = [
    "codegen",
    "ffi",
    "proc_blocks/*",
    "rune",
    "runic-types",
    "runtime",
    "syntax",
    "xtask"
]
exclude = [ "examples/*" ]

[profile.release]
debug = true
