[workspace]
resolver = "2"
members = [
    "crates/*",
    "images/runicos-base/*",
    "integration-tests",
    "bindings/native",
]

[patch.crates-io]
#serde_yaml = { git = "https://github.com/hotg-ai/serde-yaml", branch = "spans" }
