sign-commit = true
consolidate-commits = true
consolidate-pushes = true
# We'll tag manually
tag = false
# If we use dev versions (e.g. "0.9.3-dev") then we won't be able to patch
# our internal crates with a local version.
dev-version = false
