[package]
name = "noise-filtering"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runic-types = { path = "../../crates/runic-types" }
libm = "0.2.1"
paste = "1.0.5"
rune-proc-blocks = { path = "../proc-blocks" }
