[package]
name = "hotg-rune-runtime"
version = "0.4.0-dev"
edition = "2018"
authors = ["The Rune Developers <admin@hotg.ai>"]
license = "MIT OR Apache-2.0"
homepage = "https://hotg.dev/"
repository = "https://github.com/hotg-ai/rune"
categories = ["science", "wasm"]
keywords = ["rune", "runtime", "tinyml", "container", "machine", "learning"]
description = "Common abstractions and utilities used by Rune runtimes."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
hound = { version = "3.4.0", optional = true }
image = { version = "0.23.14", optional = true }
log = "0.4.14"
rand = { version = "0.8.3", optional = true }
hotg-rune-core = { path = "../rune-core", version = "0.4.0-dev", features = ["std"] }
thiserror = "1.0.24"

[features]
default = ["builtins"]
builtins = ["hound", "image", "rand", "rand/small_rng"]
