[package]
name = "rune-runtime"
version = "0.4.0-dev"
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
edition = "2018"
description = "Common abstractions and utilities used by Rune runtimes."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
hound = { version = "3.4.0", optional = true }
image = { version = "0.23.14", optional = true }
log = "0.4.14"
rand = { version = "0.8.3", optional = true }
rune-core = { path = "../rune-core", features = ["std"] }
thiserror = "1.0.24"

[features]
default = ["builtins"]
builtins = ["hound", "image", "rand", "rand/small_rng"]
