[package]
name = "rune-proc-blocks"
version = "0.4.0-dev"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rune-proc-block-macros = { path = "../macros" }
rune-core = { path = "../../crates/rune-core", default-features = false }
serde = { version = "1.0.126", default-features = false, features = ["derive", "alloc"] }
