[package]
name = "rune-proc-blocks"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rune_proc-block-macros = { path = "../macros" }
runic-types = { path = "../../crates/runic-types", default-features = false }
serde = { version = "1.0.126", default-features = false, features = ["derive", "alloc"] }
