[package]
name = "hotg-runicos-base-runtime"
version = "0.6.1-dev"
edition = "2018"
authors = ["The Rune Developers <developers@hotg.ai>"]
license = "MIT OR Apache-2.0"
homepage = "https://hotg.dev/"
repository = "https://github.com/hotg-ai/rune"
categories = ["science", "wasm"]
keywords = ["rune", "runtime", "tinyml", "container"]
description = "The runtime side of the runicos/base image."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
hotg-rune-core = { path = "../../../crates/rune-core", version = "^0.6.1-dev", features = ["std"] }
hotg-rune-runtime = { path = "../../../crates/runtime", version = "^0.6.1-dev", features = ["builtins"] }
hotg-rune-wasmer-runtime = { path = "../../../crates/wasmer-runtime", version = "^0.6.1-dev", optional = true }
hotg-rune-wasm3-runtime = { path = "../../../crates/wasm3-runtime", version = "^0.6.1-dev", optional = true }
log = "0.4.14"
rand = "0.8.4"
serde_json = { version = "1" }
# Note: This doesn't cross-compile due to https://github.com/boncheolgu/tflite-rs/issues/49
tflite = { version = "0.9.5", optional = true }
wasmer = { version = "2.0.0", optional = true }
wasmer-vm = { version = "2.0.0", optional = true }
wasm3 = { version = "0.2.0", optional = true }

[features]
default = ["tflite", "wasmer-runtime"]
wasmer-runtime = ["hotg-rune-wasmer-runtime", "wasmer", "wasmer-vm"]
wasm3-runtime = ["hotg-rune-wasm3-runtime", "wasm3"]

[dev-dependencies]
syn = { version = "1.0.73", features = ["full", "extra-traits"] }
