[package]
name = "hotg-runicos-base-runtime"
version = "0.10.0"
edition = "2018"
authors = ["The Rune Developers <developers@hotg.ai>"]
license = "MIT OR Apache-2.0"
homepage = "https://hotg.dev/"
repository = "https://github.com/hotg-ai/rune"
categories = ["science", "wasm"]
keywords = ["rune", "runtime", "tinyml", "container"]
description = "The runtime side of the runicos/base image."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
hotg-rune-core = { path = "../../../crates/rune-core", version = "^0.10.0", features = ["std"] }
hotg-rune-runtime = { path = "../../../crates/runtime", version = "^0.10.0", features = ["builtins", "wasm3"] }
hotg-runecoral = { version = "0.3.6", optional = true }
log = "0.4.14"
rand = "0.8.4"
serde_json = { version = "1" }
wasm3 = { version = "0.3.1", optional = true }
wasmer = { version = "2.0.0", optional = true }
wasmer-vm = { version = "2.0.0", optional = true }

[features]
default = ["wasmer-runtime", "tensorflow-lite"]
tensorflow-lite = ["hotg-runecoral"]
wasm3-runtime = ["hotg-rune-runtime/wasm3", "wasm3"]
wasmer-runtime = ["hotg-rune-runtime/wasmer", "wasmer", "wasmer-vm"]

[dev-dependencies]
syn = { version = "1.0.73", features = ["full", "extra-traits"] }
