[package]
name = "runicos-base-runtime"
version = "0.1.0"
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
log = "0.4.14"
rune-runtime = { path = "../../../crates/runtime", features = ["builtins"] }
runic-types = { path = "../../../crates/runic-types" }
serde_json = { version = "1" }
tflite = { version = "0.9.5", optional = true }

[features]
default = ["tflite"]
