[package]
name = "identity"
version = "0.5.2"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-core = { git = "https://github.com/hotg-ai/rune", tag = "nightly" }
hotg-rune-proc-blocks = { git = "https://github.com/hotg-ai/rune", tag = "nightly" }

[workspace]
