[package]
name = "normalize"
version = "0.5.1"
authors = ["The Rune Developers <developers@hotg.ai>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-proc-blocks = { path = "../proc-blocks", version = "^0.5.0"}
