[package]
name = "rune_py"
version = "0.5.0"
authors = ["The Rune Developers <developers@hotg.ai>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
test = false
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fft = { path = "../../proc-blocks/fft", version = "^0.5.0"}
image-normalization = { path = "../../proc-blocks/image-normalization", version = "^0.5.0"}
noise-filtering = { path = "../../proc-blocks/noise-filtering", version = "^0.5.0"}
normalize = { path = "../../proc-blocks/normalize", version = "^0.5.0"}
numpy = "0.13.1"
paste = "1.0.5"
pyo3 = { version = "0.13.2", features = ["extension-module", "abi3", "abi3-py36"] }
hotg-rune-proc-blocks = { path = "../../proc-blocks/proc-blocks", version = "^0.5.0"}
hotg-rune-core = { path = "../../crates/rune-core", version = "^0.5.1-dev"}

[[test]]
name = "python-unittest"
path = "tests/python-unittest.rs"
harness = false

[package.metadata.maturin]
requires-dist = ["numpy~=1.15"]
