[package]
name = "runicos-base-wasm"
version = "0.4.0-dev"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.wasm32-unknown-unknown.dependencies]
dlmalloc = { version = "0.2.1", features = ["global"] }
log = "0.4.14"
rune-core = { path = "../../../crates/rune-core", version = "0.4.0-dev" }
serde = { version = "1.0.126", default-features = false }
serde-json-core = { version = "0.4.0", default-features = false }
serde_json = { version = "1.0.64", features = ["alloc"], default-features = false }
