[package]
name = "hotg-runicos-base-wasm"
version = "0.5.4-dev"
edition = "2018"
authors = ["The Rune Developers <developers@hotg.ai>"]
license = "MIT OR Apache-2.0"
homepage = "https://hotg.dev/"
repository = "https://github.com/hotg-ai/rune"
categories = ["science", "wasm"]
keywords = ["rune", "tinyml", "container", "machine", "learning"]
description = "The WebAssembly side of the runicos/base image."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.wasm32-unknown-unknown.dependencies]
dlmalloc = { version = "0.2.1", features = ["global"] }
log = "0.4.14"
hotg-rune-core = { path = "../../../crates/rune-core", version = "^0.5.4-dev"}
serde = { version = "1.0.126", default-features = false }
serde-json-core = { version = "0.4.0", default-features = false }
serde_json = { version = "1.0.64", features = ["alloc"], default-features = false }

[dependencies]
