[package]
name = "image-normalization"
version = "0.5.2"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = { version = "0.2.14", default-features = false }
hotg-rune-core = { path = "../../crates/rune-core", version = "^0.5.2" }
hotg-rune-proc-blocks = { path = "../proc-blocks", version = "^0.5.2" }
