[alias]
xtask = "run --package xtask --bin xtask --"
rune = "run --package hotg-rune-cli --"
integration-tests = "run --package hotg-rune-integration-tests --"
it = "integration-tests"

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
