[package]
name = "audio_float_conversion"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runic-types = { path = "../../runic-types" }
rune-pb-core = { path = "../pb-core" }

[dev-dependencies]
pretty_assertions = "0.7.2"