[package]
name = "normalize"
version = "0.1.0"
authors = ["Kartik Thakore <kartik@thakore.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runic-types = { path = "../../runic-types "}

[dev-dependencies]
rand = "0.8.3"
