[package]
name = "rune"
version = "0.1.0"
authors = ["HOTG-AI"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
no-std-compat = "0.4.1"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib"]


[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
codegen-units = 1
lto = true




