[package]
name = "rune"
version = "0.2.0"
authors = ["Kartik Thakore <kartik@thakore.ai>", "Akshay Sharma <akshay@sharma.ai>"]
edition = "2018"
license = "Apache 2.0"
keywords = ["tinyml", "container"]


[dependencies]
runic-types = { path = "../runic-types" }
clap = "2.33.3"
env_logger = "0.8.1"
log = "0.4.11"
rand = "0.8.3"
runic-transform = { path = "../runic-transform" }
wasmer-runtime = "0.17.1"
wasmer-runtime-core = "0.17.1"
tflite = "0.9.2"
anyhow = "1.0.38"
rune-syntax = { path = "../syntax" }
codespan-reporting = "0.11.0"
rune-codegen = { path = "../codegen" }
dirs = "3.0.1"

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.7"

