[package]
name = "label"
version = "0.5.1"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-proc-blocks = { path = "../proc-blocks", version = "^0.5.0"}

[dev-dependencies]
hotg-rune-core = { path = "../../crates/rune-core", version = "0.5.0"}
