[package]
name = "label"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rune-proc-blocks = { path = "../proc-blocks" }

[dev-dependencies]
runic-types = { path = "../../crates/runic-types" }
