name: rune_dart
description: Dart bindings to the Rune runtime.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.4 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

ffigen:
  name: Rune
  description: Bindings to the Rune runtime.
  output: "lib/generated_bindings.dart"
  headers:
    entry-points:
      - "rune.h"
    include-directives:
      - "rune.h"
  compiler-opts:
    - "-I/usr/lib/clang/12.0.1/include/"
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides
