[package]
name = "noise-reduction"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runic-types = { path = "../../runic-types" }

[dev-dependencies]
once_cell = "1.7.2"
quickcheck = "1.0.3"
