[package]
name = "fft"
version = "0.1.0"
authors = ["Kartik Thakore <kartik@thakore.ai"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runic-types = { path = "../../runic-types" }
hound = "3.4"
sonogram = {git = "https://github.com/hotg-ai/sonogram"}
mel = "0.3.0"
nalgebra = "0.26.1"
