[package]
name = "rune-pb-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rune-pb-macros = { path = "../macros" }
runic-types = { path = "../../runic-types" }
