image: runicos/base

pipeline:
  # All the normal stages from our sine demo
  rand:
    capability: RAND
    outputs:
      - type: F32
        dimensions: [1]
  mod360:
    proc-block: "hotg-ai/rune#proc_blocks/modulo"
    inputs:
      - rand
    outputs:
      - type: F32
        dimensions: [1]
    args:
      modulus: 360.0
  sine:
    model: "./sinemodel.tflite"
    inputs:
      - mod360
    outputs:
      - type: F32
        dimensions: [1]
  serial:
    out: serial
    inputs:
      - rand

  # Add another stage which captures the output from all the other stages so
  # we can inspect it
  debug_output:
    out: serial
    inputs:
      - rand
      - mod360
      - sine
