[package]
name = "rune-wasmer-runtime"
version = "0.1.0"
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
log = "0.4.14"
rune-runtime = { path = "../runtime" }
rune-core = { path = "../rune-core" }
wasmer = "1.0.2"
wasmer-types = "1.0.2"
wasmer-vm = "1.0.2"

[dev-dependencies]
tempfile = "3.2.0"
