name: Benchmarks

on:
  push:
    branches:
    - master

jobs:
  benchmark:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust
        run: |
          rustup default nightly-2021-05-09
          rustup target add wasm32-unknown-unknown
          rustc --version --verbose
          rustup show
      - name: Install cargo-criterion
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-criterion
          version: latest
      - name: Execute the Benchmarks
        run: |
          cd runtime
          cargo criterion
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v2
        with:
          name: benchmarks
          path: target/criterion
