name: Nightly

on:
  schedule:
  - cron: '0 0 * * *' # midnight UTC
  workflow_dispatch:

env:
  # Only run this action if it was scheduled and there were commits within the
  # last X hours/days
  ACTIVITY_THRESHOLD: "24 hours"

jobs:
  # Check to see whether there have been any commits since the last run,
  # letting us skip subsequent steps if there haven't.
  # https://github.community/t/trigger-action-on-schedule-only-if-there-are-changes-to-the-branch/17887
  check_date:
    runs-on: ubuntu-18.04
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: Check for changes within the activity threshold
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="${{ env.ACTIVITY_THRESHOLD }}" ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build:
    name: Build release artifacts for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-18.04
            artifact_name: "target/rune.*.zip"
            asset_name: rune-linux
          # - name: windows
          #   os: windows-latest
          #   artifact_name: "target/rune.*.zip"
          #   asset_name: rune-windows
          - name: macos
            os: macos-latest
            artifact_name: "target/rune.*.zip"
            asset_name: rune-macos
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown x86_64-unknown-linux-musl
      - name: Build
        run: cargo xtask dist
        env:
          RUST_LOG: info,xtask=debug
      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}

  python:
    name: Python Bindings
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Compile the Wheel
        run: |
          pip3 install maturin
          maturin build --manifest-path proc_blocks/python/Cargo.toml \
                        --bindings pyo3 \
                        --manylinux off \
                        --no-sdist \
                        --release
          pip3 install target/wheels/*.whl
          python3 -c 'from proc_blocks import Normalize; n = Normalize(); print(n([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))'
      - name: Upload Wheels
        uses: actions/upload-artifact@v2
        with:
          name: python-wheel-${{ matrix.os }}
          path: target/wheels/*.whl

  create-release:
    name: Create Nightly Release
    runs-on: ubuntu-18.04
    needs:
      - build
      - python
      - check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch Pre-Compiled Binaries
        uses: actions/download-artifact@v2
        with:
          path: nightly
      - name: Move all up
        run: mv nightly/**/* nightly/
      - name: Print Artifacts
        run: ls -la nightly
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly Release"
          files: |
            nightly/*.zip
