[package]
name = "identity"
version = "0.5.2"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-core = { path = "../../crates/rune-core", version = "^0.8.0" }
hotg-rune-proc-blocks = { path = "../../crates/proc-blocks", version = "^0.8.0" }
