version: 1
image: runicos/base
pipeline:
  random:
    capability: RAND
    outputs:
      - type: f32
        dimensions: [1]
  some_model:
    model: ../../../examples/sine/sinemodel.tflite
    inputs:
      - another_model
    outputs:
      - type: f32
        dimensions: [1]
  another_model:
    model: ../../../examples/sine/sinemodel.tflite
    inputs:
      - some_model
    outputs:
      - type: f32
        dimensions: [1]

